#!/usr/bin/env python3
"""Crop the generated header source to the 1500x500 a social banner needs.

The source is generated by the Gemini image API at 21:9 (see PROMPTS.md);
this only reframes it. Content is centre-weighted because X crops the
edges of a header differently on mobile and desktop.

    python3 src/make-header.py
"""
from PIL import Image
from pathlib import Path

out = Path(__file__).resolve().parent.parent
src = Image.open(out / "src" / "oif-header-source-21x9.png").convert("RGB")

W, H = src.size
target_h = int(W / 3)                      # 1500x500 is 3:1
if target_h <= H:
    top = (H - target_h) // 2
    im = src.crop((0, top, W, top + target_h))
else:                                      # source too short: pad with its own background
    bg = src.getpixel((5, 5))
    im = Image.new("RGB", (W, target_h), bg)
    im.paste(src, (0, (target_h - H) // 2))

im.resize((1500, 500), Image.LANCZOS).save(out / "oif-header-1500x500.png", optimize=True)
print(f"wrote {out / 'oif-header-1500x500.png'}")
